definitions:
  models.Item:
    description: Represents an item tied to an order.
    properties:
      description:
        example: A description
        type: string
      itemCode:
        example: STUFF-1
        type: string
      lineItemId:
        example: 1
        type: integer
      quantity:
        example: 1337
        type: integer
    type: object
  models.Order:
    description: Represent an order of a customer with the order date and one or more
      item(s).
    properties:
      customerName:
        example: Marvin
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        type: array
      orderId:
        example: 1
        type: integer
      orderedAt:
        example: "2022-02-22T20:00:00.0000000+00:00"
        type: string
    type: object
  order_requests.ItemCreate:
    description: Represents a request payload for an item tied to an order create
      request.
    properties:
      description:
        description: This is the item description
        example: A description
        type: string
      itemCode:
        description: This is the item code
        example: STUFF-1
        type: string
      quantity:
        description: This is the item quantity
        example: 10
        type: integer
    required:
    - description
    - itemCode
    - quantity
    type: object
  order_requests.ItemUpdate:
    description: Represents a request payload for an item tied to an order create
      request.
    properties:
      description:
        description: This is the item description
        example: A (new) description
        type: string
      itemCode:
        description: This is the item code
        example: STUFF-1
        type: string
      lineItemId:
        description: This is the item ID
        example: 1
        type: integer
      quantity:
        description: This is the item quantity
        example: 1337
        type: integer
    required:
    - description
    - itemCode
    - quantity
    type: object
  order_requests.OrderCreate:
    description: Represents a request payload for order creation.
    properties:
      customerName:
        description: This is the customer name
        example: Marvin
        type: string
      items:
        description: This is the order items
        items:
          $ref: '#/definitions/order_requests.ItemCreate'
        type: array
    required:
    - customerName
    - items
    type: object
  order_requests.OrderUpdate:
    description: Represents a request payload for order update.
    properties:
      customerName:
        description: This is the customer name
        example: Marvin
        type: string
      items:
        description: This is the order items
        items:
          $ref: '#/definitions/order_requests.ItemUpdate'
        type: array
    required:
    - items
    type: object
  responses.Error:
    description: Represents the default error response payload.
    properties:
      message:
        example: something is wrong
        type: string
      status:
        example: error
        type: string
    type: object
  responses.WithDataList-models_Order:
    properties:
      count:
        example: 1
        type: integer
      data:
        items:
          $ref: '#/definitions/models.Order'
        type: array
      message:
        example: success
        type: string
    type: object
  responses.WithRowsAffected:
    description: Represents a response payload for any operations with affected row
      count from the database.
    properties:
      count:
        example: 13
        type: integer
      message:
        example: success
        type: string
    type: object
  responses.WithSingleData-models_Order:
    properties:
      data:
        $ref: '#/definitions/models.Order'
      message:
        example: success
        type: string
    type: object
info:
  contact:
    email: rocky@lazycats.id
    name: API Support
    url: https://rocky.my.id/
  description: This is a REST API for a custom shop ordering system.
  title: Hacktiv8 Golang Assignment 2 - Orders
  version: "1.0"
paths:
  /orders:
    get:
      description: Fetch all order(s) from the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.WithDataList-models_Order'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Fetch all orders
      tags:
      - orders
    post:
      consumes:
      - application/json
      description: Creates a new order and persists them to the database.
      parameters:
      - description: Create Order Request
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/order_requests.OrderCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.WithSingleData-models_Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Create order
      tags:
      - orders
  /orders/{id}:
    delete:
      description: Deletes an order with the given ID from the database.
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.WithRowsAffected'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Delete order
      tags:
      - orders
    get:
      description: Fetch an order by its ID from the database.
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.WithSingleData-models_Order'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Fetch single order
      tags:
      - orders
    put:
      consumes:
      - application/json
      description: Updates an order with the given ID and payload on the database.
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Order Payload
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/order_requests.OrderUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.WithSingleData-models_Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.Error'
      summary: Update order
      tags:
      - orders
swagger: "2.0"
